# Generated by Django 5.1.15 on 2026-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número sequencial na planilha de origem (INPI/NIT-IFMA).')),
                ('tipo', models.CharField(db_index=True, max_length=60)),
                ('titulo', models.TextField()),
                ('campus', models.CharField(blank=True, db_index=True, max_length=120)),
                ('autores', models.CharField(blank=True, max_length=500)),
                ('numero_processo', models.CharField(blank=True, max_length=100)),
                ('data_deposito', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=60)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Propriedade Intelectual',
                'verbose_name_plural': 'Registros de Propriedade Intelectual',
                'ordering': ['-data_deposito', 'numero'],
            },
        ),
    ]
