# Generated by Django 5.1.15 on 2026-09-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eixos', '0002_seed_eixos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_prioritaria', models.CharField(max_length=300)),
                ('entregavel', models.CharField(max_length=300)),
                ('lideranca_proposta', models.CharField(max_length=300)),
                ('horizonte_inicio_meses', models.PositiveSmallIntegerField()),
                ('horizonte_fim_meses', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('dados_a_validar', 'Dados a validar'), ('validado', 'Validado')], default='dados_a_validar', max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_de_acao', to='eixos.eixo')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'ordering': ['eixo__ordem', 'ordem', 'horizonte_inicio_meses'],
            },
        ),
    ]
